version: 2.1

jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.9.5
    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
      GRAALVM_HOME: /home/circleci/graalvm-ce-java8-21.1.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}-{{ checksum ".circleci/config.yml" }}
            - v1-dependencies-
      - run:
          name: Install Clojure
          command: |
            wget https://download.clojure.org/install/linux-install-1.10.1.447.sh
            chmod +x linux-install-1.10.1.447.sh
            sudo ./linux-install-1.10.1.447.sh
      - run:
          name: Install native dev tools
          command: |
            sudo apt-get update
            sudo apt-get -y install build-essential zlib1g-dev
      - run:
          name: Download GraalVM
          command: |
            cd ~
            if ! [ -d graalvm-ce-java8-21.1.0 ]; then
              curl -O -sL  https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.1.0/graalvm-ce-java8-linux-amd64-21.1.0.tar.gz
              tar xzf graalvm-ce-java8-linux-amd64-21.1.0.tar.gz
            fi
      - run:
          name: Install native-image
          command: |
            "$GRAALVM_HOME/bin/gu" install native-image || true
      - run:
          name: Build binary
          command: |
            cd ~/repo
            pwd
            ls -latrF
            ./compile
          no_output_timeout: 30m
      - save_cache:
          paths:
            - ~/.m2
            - ~/graalvm-ce-java8-21.1.0
          key: v1-dependencies-{{ checksum "project.clj" }}--{{ checksum ".circleci/config.yml" }}
      - store_artifacts:
          path: ~/repo/cnf
          destination: cnf

workflows:
  build:
    jobs:
      - build
